
version: 1.0.{build}

branches:

  only:

    - master

  except:

    - gh-pages

skip_commits:

    files:

    - docs/*

    - README.md

image: Visual Studio 2015

init:

    - git config --global core.autocrlf input

clone_folder: c:\projects\dictionary-csv-extensions

assembly_info:
    patch: true

    file: AssemblyInfo.*

    assembly_version: "0.1.{build}"

    assembly_file_version: "{version}"

    assembly_informational_version: "{version}"

nuget:

    account_feed: true

    project_feed: false

    disable_publish_on_pr: true

platform: Any CPU

configuration: Release

build:

  parallel: false

  project: CsvDictionary.sln

  publish_nuget: true

  publish_nuget_symbols: true

  include_nuget_references: true

  verbosity: minimal

before_build:

artifacts:

    - path: CsvDictionary.zip

    - path: bin\$(configuration)

      name: CsvDictionary

    - path: '**\*.nupkg'

deploy:

#    - provider: GitHub
#
#      artifact: /.*\.nupkg/
#
#      draft: false
#
#      prerelease: false
#
#      on:
#
#        branch: master
#
#        appveyor_repo_tag: false

before_deploy:

